config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  root 'home#index'

  get 'exercises/group/:id' => 'exercises#group', as: 'exercises_group'

  get 'programs/filter' => 'programs#filter', as: 'program_filter'

  get 'programs/assign_to_user' => 'programs#assign_to_user', as: 'assign_program'

  get '/programs' => 'programs#all_programs', as: 'all_programs'

  get '/programs/:id' => 'programs#common_program', as: 'common_program'

  get '/individual' => 'programs#individual', as: 'individual_program'
  post '/create_individual' => 'programs#create_individual', as: 'create_individual_program'

  resources :exercises, only: [:index, :show]
  resources :users do
    resources :programs, controller: 'programs', as: 'training_programs'
    resources :parameters, controller: 'parameters'
    resources :events, controller: 'events'
  end

  get 'training_days/:id/edit' => 'training_days#edit', as: 'edit_training_day'

  get 'training_days/:id/change_exercise' => 'training_days#change_exercise', as: 'change_exercise'

  delete 'training_days/:id/delete_exercise' => 'training_days#delete_exercise', as: 'delete_exercise'

end

app/models/program_type.rb
class ProgramType < ActiveRecord::Base
  has_many :training_programs
  validates :name, presence: true
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :check_user, only: [:index]
  before_action :program_info, only: [:show, :common_program]
  before_action  :authenticate_user!, except: [:all_programs, :common_program, :assign_to_user, :filter]
  def index
    @user = current_user
    @programs = @user.training_programs
  end

  def show
  end

  def edit
    @program = TrainingProgram.find(params[:id])
    @exercises = Exercise.all
  end

  def update
    @program = TrainingProgram.find(params[:id])
    if @program.update(program_params)
      redirect_to [current_user, @program]
    else
      render 'edit'
    end
  end

  def individual
    @program = TrainingProgram.new
  end

  def create_individual
    #render text: individual_params[:joint_pain]
    #@program = TrainingProgram.generate_program(individual_params, current_user)
    @program = TrainingProgram.generate_program(individual_params, current_user)
    #render json: @program.training_days[0].training_day_exercises
    redirect_to user_training_program_path(current_user, @program)
  end

  def filter
    @programs = TrainingProgram.filter(params.slice(:body_type, :program_type, :male_type))
    respond_to do |format|
      format.js
    end
  end

  def assign_to_user
    @program = TrainingProgram.find(params[:program])
    unless current_user.has_program? @program
      @program.duplicate_program(current_user)
    end
    respond_to do |format|
      format.js
    end
  end

  def all_programs
    @programs = TrainingProgram.includes(:program_type).all
    @body_types = TrainingProgram.body_types
    @male_types = User.male_types
  end

  def common_program
    render action: 'show'
  end

  private
  def program_info
    @program = TrainingProgram.find(params[:id])
    info = @program.days_count
    @days_count = info[0]
    @ex_count = info[1]
    @author = @program.get_author
  end

  def program_params
    params.require(:training_program).permit(:name, :description, :program_type_id, :body_type, :male_type, :program_image)
  end

  def individual_params
    params.permit(:height, :weight, :program_type_id, :body_type, :male_type, :age, :workout_1, :workout_2, :workout_3, :user_id, joint_pain: [])
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_days.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <h1> План тренувань </h1>
    <hr class="section-heading-spacer">
  </div>
</div>
<div class="row" id="program-plan">
  <div class="col-xs-4 col-sm-2 col-md-2 col-lg-2">
    <div class="tabable">
      <ul class="nav nav-pills nav-stacked">
        <% active = false %>
        <% @program.training_days.each_with_index  do |day, index| %>
            <% if day.has_exercises? %>
              <% if !active %>
                <li class="active">
                <% active = true %>
              <% else %>
                <li>
              <% end %>
                  <a data-toggle="tab" href="#day<%= index+1 %>">День <%= index+1 %></a>
                </li>
            <% else %>
                <li class="disabled">
                  <a href="#day<%= index+1 %>">День <%= index+1 %></a>
                </li>
            <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-xs-8 col-sm-10 col-md-10 col-lg-10 tab-content">
    <% active = false %>
    <% @program.training_days.each_with_index  do |day, index| %>
      <div
      <% if !active %>
        <%= "id=day#{index+1}" %> class="tab-pane fade in active col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <% active = true %>
      <% else %>
        <%= "id=day#{index+1}"%> class="tab-pane fade col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <% end %>
        <h3>
          <%=  (day.description.nil? || day.description.empty?) ? "День #{index + 1}" : "#{day.description}"   %>
        </h3>
      <% day.training_day_exercises.each do |exercise_day| %>
        <%= link_to exercise_day.exercise, class: 'day-exercise-link col-xs-12 col-sm-12 col-md-12 col-lg-12' do %>
          <div class="training-day-exercise row col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
              <%= image_tag(exercise_day.exercise.exercise_image.url) %>
            </div>
            <div class="day-exercise-content col-xs-12 col-sm-6 col-md-9 col-lg-9">
              <h4>
                <%= exercise_day.exercise.name %>
              </h4>
              <div>
                <%= image_tag('common/sets.svg') %>
                <p class="inline">Кількість підходів: <%= exercise_day.sets %></p>
              </div>
              <div>
                <%= image_tag('common/repetitions.svg')%>
                <p class="inline">Кількість повторів: <%= exercise_day.repetitions %></p>
              </div>
              <div>
                <%= image_tag('common/rest.svg')%>
                <p class="inline">Час між підходами: <%= exercise_day.rest %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/programs/_form.html.erb
<%= form_tag(edit_training_day_path(day: day, index: index), method: :get, remote: true, class: 'form-group') do %>
    <% if !errors.nil? %>
        <div id="error_explanation" class=" alert alert-danger">
          <h2><%= pluralize(errors.count, "error") %> prohibited this exercise from being saved:</h2>
          <ul>
            <% errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <%= text_field_tag :sets, nil, placeholder: 'Кількість підходів',class: 'form-control' %>
    <%= text_field_tag :repetitions, nil,  placeholder: 'Кількість повторів',class: 'form-control' %>
    <%= text_field_tag :rest, nil, placeholder: 'Час відпочинку',class: 'form-control' %>
    <%= select_tag :exercise, options_from_collection_for_select(exercises, 'id', 'name'),class: 'form-control select'%>
    <%= submit_tag 'Додати', class: 'form-control btn btn-md btn-primary'%>
<% end %>

app/views/programs/_programs_list.html.erb
<% programs.each do |program| %>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
      <div class="image-wrapper overlay-fade-in">
        <%= image_tag(program.program_image.url) %>
        <div class="image-overlay-content">
          <h2>.overlay-fade-in</h2>
          <p class="price">$99.99</p>
          <%= link_to 'Get it', program_path(program), class: 'button' %>
        </div>
      </div>
    </div>
<% end %>

app/views/programs/_training_day.html.erb
<div class="list-group">
  <div class="list-group-item">
    <h3 id="day-title">
      <%= "День #{index}"%>
    </h3>
    <h5 id="day-description">
      <%= "(#{day.description})" unless day.description.nil? || day.description.empty?  %>
    </h5>
  </div>


    <% if day.training_day_exercises.empty? %>
      <div class="list-group-item text-center">
        <%= image_tag('common/clocks.svg', class: 'clock-image')%>
        <h5>
          День відпочинку
        </h5>
      </div>
    <% else %>
        <% day.training_day_exercises.each do |exercise|%>
          <div class="list-group-item">
            <div class="edit-exercise-container" id="<%="ex_#{exercise.id}"%>">
              <%= render partial: 'programs/training_day_exercise', locals: {day_exercise: exercise, index: index} %>
            </div>
          </div>
        <% end %>
    <% end %>
  <div class="list-group-item">
    <%= link_to 'Додати вправу',  '#', 'data-target' => "#myModal_#{day.id}", 'data-toggle' => 'modal', class:'btn btn-md btn-success'  %>
  </div>
</div>

<div class="modal fade" id='<%= "myModal_#{day.id}" %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"> Додати вправу </h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'programs/form', locals: {day: day, errors: nil, exercises: @exercises, index: index} %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/programs/_training_day_exercise.html.erb
<div class="exercise">
  <h5>
    <%= day_exercise.exercise.name %>
  </h5>
  <div>
    <%= image_tag('common/sets.svg') %>
    <p class="inline"><%= day_exercise.sets %></p>
    <%= image_tag('common/repetitions.svg')%>
    <p class="inline"> <%= day_exercise.repetitions %></p>
    <%= image_tag('common/rest.svg')%>
    <p class="inline"> <%= day_exercise.rest %></p>
  </div>
</div>
<%= link_to 'Редагувати',  '#', 'data-target' => "#myModal_exercise#{day_exercise.id}", 'data-toggle' => 'modal', class: 'btn btn-sm btn-warning'  %>
<%= link_to 'Видалити', delete_exercise_path(id: day_exercise.id, index: index),  method: :delete, data: {confirm: 'Видалити вправу?'}, remote: true, class: 'btn btn-sm btn-danger' %>
<div class="modal fade" id='<%= "myModal_exercise#{day_exercise.id}" %>' tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Редагувати вправу</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'programs/partials/edit_exercise_form', locals: { day_exercise: day_exercise, errors: nil, exercises: @exercises, index: index} %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/programs/all_programs.html.erb
<section id="features">
  <div class="container">
    <div class="section-header">
      <h2 class="section-title text-center"> Програми </h2>
      <p class="text-center"> Знайдіть необхідну Вам програму залежно від тілобудови, статі та та поставленої мети</p>
    </div>
    <div class="row">
      <div class="col-sm-6 col-lg-6 col-md-6 col-xs-12">
        <%= image_tag('programs/all-programs.png', class: 'img-responsive') %>
      </div>
      <div class="col-sm-6 col-lg-6 col-md-6 col-xs-12">
        <div class="media service-box">
          <div class="pull-left">
            <i class="fa fa-lightbulb-o"></i>
          </div>
          <div class="media-body">
            <h4 class="media-heading"> Мета </h4>
            <p> Визначте ціль своїх тренувань: набрати м’язеву масу, схуднути чи покращити силові показники </p>
          </div>
        </div>

        <div class="media service-box">
          <div class="pull-left">
            <i class="fa fa-venus-mars"></i>
          </div>
          <div class="media-body">
            <h4 class="media-heading"> Стать </h4>
            <p> Вкажіть вашу стать. Чоловічі та жіночі програми кардинально різні. </p>
          </div>
        </div>

        <div class="media service-box">
          <div class="pull-left">
            <i class="fa fa-male"></i>
          </div>
          <div class="media-body">
            <h4 class="media-heading"> Тілобудова </h4>
            <p> Будова вашого тіла - основний критерій при створенні програми, оскільки він впливає на всі характеристики програми: інтенсивність, тривалість, набір вправ. </p>
          </div>
        </div>

        <div class="media service-box">
          <div class="pull-left">
            <i class="fa fa-percent"></i>
          </div>
          <div class="media-body">
            <h4 class="media-heading"> Точність </h4>
            <p> Жоден алгоритм не може замінити професійного тренера, адже лише він може абсолютно точно підібрати Вам програму та особисто конролювати процес тренування. </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="container" id="all_programs">
  <div class="row">
    <%= form_tag(program_filter_path, method: :get,  remote: true, class: 'form-group col-xs-12 col-sm-12 col-md-12 col-lg-12') do %>
        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 field">
          <%= select_tag :program_type, options_from_collection_for_select(@program_types, 'id', 'name'),{include_blank: 'Ціль тренувань', class: 'form-control inline'} %>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 field">

          <%= select_tag :male_type, options_for_select(@male_types), {include_blank: 'Стать', class: 'form-control'}%>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 field">
          <%= select_tag :body_type, options_for_select(@body_types), {include_blank: 'Тілобудова', class: 'form-control'}%>

          <%= link_to '#', class:'body-tooltip', title: "#{image_tag('common/bodytype_tooltip.jpg', class: 'tooltip-image')}", 'data-toggle'=>'tooltip' do %>
            <i id="body-type-glyphicon" class="glyphicon glyphicon-question-sign"></i>
          <% end %>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 field">
          <%= submit_tag 'Підібрати', class: 'form-control col-xs-3 col-sm-3 col-md-3 col-lg-3' %>
        </div>
    <% end %>
  </div>
  <div class="row programs-list">
    <%= render partial: 'programs/partials/programs_list', locals: {programs: @programs} %>
  </div>
</div>

app/views/programs/assign_to_user.js.erb
$("#assign-program").html("<%= escape_javascript(render partial: 'programs/partials/assign_program') %>");

app/views/programs/edit.html.erb
<div class="container main-container edit-program">
  <h1>Редагування програми</h1>
  <hr>
  <div class="row">
  <%= form_for [current_user, @program], class: 'form-group' do |f| %>

        <!-- left column -->
        <div class="col-md-3">
          <div class="text-center">
            <%= image_tag(@program.program_image, class:'avatar img-thumbnail')%>
            <h6>Завантажте нове зображення</h6>
            <%= f.file_field :program_image %>
          </div>
        </div>
        <!-- edit form column -->
        <div class="col-md-9 personal-info">
          <h3>Основна інформація</h3>
              <label class="col-lg-3 control-label"> Назва: </label>
              <div class="col-lg-8">
                <%= f.text_field :name, class:'form-control'%>
              </div>
              <label class="col-lg-3 control-label">Опис:</label>
              <div class="col-lg-8">
                <%= f.text_area :description, rows: '15', class:'form-control'%>
              </div>
          <label class="col-lg-3 control-label"> Ціль: </label>
          <div class="col-lg-8">
            <%= f.collection_select(:program_type_id, @program_types, :id, :name ,  {prompt: true}, {class: 'form-control', include_blank: 'Будь-яка'}) %>
          </div>
          <label class="col-lg-3 control-label"> Тілобудова </label>
          <div class="col-lg-8">
            <%= f.select(:body_type, TrainingProgram.body_types.keys.to_a,  {prompt: false}, {class: 'form-control', include_blank: 'Будь-яка'}) %>
          </div>
          <label class="col-lg-3 control-label"> Стать </label>
          <div class="col-lg-8">
            <%= f.select(:male_type, TrainingProgram.male_types.keys.to_a,  {prompt: false}, {class: 'form-control', include_blank: 'Будь-яка'}) %>
          </div>
              <label class="col-md-3 control-label"></label>
              <div class="col-md-8">
                <%= f.submit 'Зберегти', class: 'btn btn-primary'%>
              </div>
        </div>

  <% end %>

  </div>
  <% tdays = @program.training_days %>
  <% i = 1%>
  <h1> План тренувань </h1>
  <hr>
  <div class="row training-days">

    <div class="col-sm-1 col-md-2 col-lg-2"></div>
    <div class="col-xs-12 col-sm-10 col-md-8 col-lg-8">
      <% tdays[0..2].each do |day| %>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
          <div class="edit-day-container inline" id= <%="day#{day.id}"%>>
            <%= render partial: 'training_day', locals: {day: day, index: i} %>
            <% i+= 1%>
          </div>
        </div>
       <% end %>
    </div>
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
  </div>
  <div class="row training-days">
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
    <div class="col-xs-12 col-sm-10 col-md-8 col-lg-8">
      <% tdays[3..5].each do |day| %>
          <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <div class="edit-day-container" id= <%="day#{day.id}"%>>
              <%= render partial: 'training_day', locals: {day: day, index: i} %>
              <% i+= 1%>
            </div>
          </div>
      <% end %>
    </div>
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
  </div>
  <% day = tdays.last %>
  <div class="row training-days">
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
    <div class="col-xs-12 col-sm-10 col-md-8 col-lg-8">
      <div class="col-sm-4 col-md-4 col-lg-4"> </div>
      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
        <div class="edit-day-container inline" id= <%="day#{day.id}"%>>
          <%= render partial: 'training_day', locals: {day: day, index: i} %>
        </div>
      </div>
      <div class="col-sm-4 col-md-4 col-lg-4"> </div>
    </div>
    <div class="col-sm-1 col-md-2 col-lg-2"></div>
  </div>

</div>

app/views/programs/filter.js.erb
$(".programs-list").html("<%= escape_javascript(render partial: 'programs/partials/programs_list', locals: { programs: @programs } ) %>");

app/views/programs/index.html.erb
<div class="container main-container">
  <div class="row text-center">
    <h1>
      Програми тренувань
    </h1>
  </div>

  <div class="row programs-list">
    <%= render partial: 'programs/partials/programs_list', locals: {programs: @programs} %>
  </div>
</div>

app/views/programs/show.html.erb
<% if @program.program_image.present? %>
 <div class="container full-width">
  <div class="row program-head">
    <div id="program-head-block">
      <h1><%= @program.name %></h1>
      <%= link_to 'Розпочати', '#', class:'btn btn-lg square-btn-wr', role: 'button' %>
    </div>
  </div>
 </div>
<% end %>
<div id="program-body" class="container main-container">
  <% unless @program.program_image.present? %>
      <div class="row text-center">
        <h1> <%= @program.name %> </h1>
        <hr class="center-spacer">
      </div>
  <% end %>
  <div class="row desc-blocks">
    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2 text-center">
      <div class="desc-block">
        <div class="block-info"> <%= !@program.program_type.nil? && @program.program_type.name.present? ? @program.program_type.name : 'Будь-яка' %> </div>
        <div class="block-title"> Ціль </div>
      </div>
    </div>
    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2 text-center">
      <div class="desc-block">
      <div class="block-info"> <%= @program.body_type.present? ? @program.body_type :  'Будь-яка' %> </div>
      <div class="block-title"> Тілобудова </div>
      </div>
    </div>
    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2 text-center">
      <div class="desc-block">
      <div class="block-info"> <%= @program.male_type.present? ? @program.male_type : 'Будь-яка' %> </div>
      <div class="block-title"> Стать </div>
      </div>
    </div>
    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2 text-center">
      <div class="desc-block">
      <div class="block-info"> <%= @days_count %> </div>
      <div class="block-title"> Кількість днів </div>
      </div>
    </div>
    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2 text-center">
      <div class="desc-block">
      <div class="block-info"> <%= @ex_count %>  </div>
      <div class="block-title"> Кількість вправ </div>
      </div>
    </div>
    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2 text-center">
      <div class="desc-block">
      <div class="block-info"> <%= @author %> </div>
      <div class="block-title"> Автор </div>
      </div>
    </div>
  </div>
  <% unless @program.description.nil? || @program.description.empty? %>
    <div class="row description-row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h1> Опис </h1>
        <hr class="section-heading-spacer">
        <p class="text-pre-line">
          <%= @program.description %>
        </p>
      </div>

    </div>
  <% end %>

  <%= render 'days' %>
  <div id="assign-program" class="row">
    <div class="col-xs-4 col-sm-2 col-md-2 col-lg-2"></div>
    <div id = "assign-pr" class="col-xs-8 col-sm-10 col-md-10 col-lg-10">
      <%= render partial: 'programs/partials/assign_program', locals: {program: @program} %>
    </div>
  </div>
</div>
<style>
  .program-head {
      background-image: url('<%= @program.program_image %>');
  }
</style>