config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  root 'home#index'

  get 'exercises/group/:id' => 'exercises#group', as: 'exercises_group'

  get 'programs/filter' => 'programs#filter', as: 'program_filter'

  get 'programs/assign_to_user' => 'programs#assign_to_user', as: 'assign_program'

  get '/programs' => 'programs#all_programs', as: 'all_programs'

  get '/programs/:id' => 'programs#common_program', as: 'common_program'

  get '/individual' => 'programs#individual', as: 'individual_program'
  post '/create_individual' => 'programs#create_individual', as: 'create_individual_program'

  resources :exercises, only: [:index, :show]
  resources :users do
    resources :programs, controller: 'programs', as: 'training_programs'
    resources :parameters, controller: 'parameters'
    resources :events, controller: 'events'
  end

  get 'training_days/:id/edit' => 'training_days#edit', as: 'edit_training_day'

  get 'training_days/:id/change_exercise' => 'training_days#change_exercise', as: 'change_exercise'

  delete 'training_days/:id/delete_exercise' => 'training_days#delete_exercise', as: 'delete_exercise'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_carousel.html.erb
<!-- Carousel
    ================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active" id="first-item">
      <div class="container">
        <div class="carousel-caption">
          <h1> Персональний фітнес-тренер </h1>
          <p> Особистий асистент для занять у спортивному залі </p>
          <p>
            <%= link_to 'Розпочати сьогодні', new_user_registration_path, class:'btn btn-lg carousel-button', role: 'button' %>
          </p>
        </div>
      </div>
    </div>
    <div class="item" id="second-item">
      <div class="container">
        <div class="carousel-caption">
          <h1> Програми тренувань </h1>
          <p> Займайтеся за програмами відомих спортсменів </p>
          <p>
            <%= link_to 'Вибрати програму', all_programs_path, class:'btn btn-lg carousel-button', role: 'button' %>
          </p>
        </div>
      </div>
    </div>
    <div class="item" id="third-item">
      <div class="container">
        <div class="carousel-caption">
          <h1> Щоденник прогресу </h1>
          <p> Слідкуйте за прогресом, проводячи заміри та відслідковуючи різницю</p>
          <p>
            <%= link_to 'Завести щоденник', user_signed_in? ? user_parameters_path(current_user) : new_user_registration_path, class:'btn btn-lg carousel-button', role: 'button' %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="https://getbootstrap.com/examples/carousel/#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="https://getbootstrap.com/examples/carousel/#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div><!-- /.carousel -->

app/views/home/_main_blocks.html.erb
<a  name="services"></a>
<div class="content-section-a">
  <div class="container">
    <div class="row center-outer">
      <div id="main-content-1" class="col-lg-5 col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading"> Готові програми тренувань </h2>
        <p class="lead">Хочете набрати м’язеву масу або скинути зайву вагу, але не знаєте, як скласти програму тренувань?
          Вибирайте готову програму залежно від поставленої мети. </p>
        <%= link_to 'Вибрати', all_programs_path, class: 'btn btn-lg square-btn' %>
      </div>
      <div class="col-lg-5 col-lg-offset-2 col-sm-6 center-inner">
        <%= image_tag('main/content-image-1.jpg', class: 'img-responsive img-rounded', id: 'content-image-1') %>
      </div>
    </div>

  </div>
  <!-- /.container -->
</div>
<!-- /.content-section-a -->

<div class="content-section-b">

  <div class="container">

    <div class="row center-outer">
      <div id="main-content-2" class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading">Відстежуйте прогрес  </h2>
        <p class="lead">
          Заводьте щоденник прогресу в особистому кабінеті для спостереженя за результатами тренувань. Ставте перед собою нові цілі та досягайте їх
        </p>
        <%= link_to 'Завести',user_signed_in? ? user_parameters_path(current_user) : new_user_registration_path, class: 'btn btn-lg square-btn' %>
      </div>
      <div class="col-lg-5 col-sm-pull-6  col-sm-6 center-inner">
        <%= image_tag('main/content-image-2.jpg', class: 'img-responsive img-rounded', id: 'content-image-2') %>
      </div>
    </div>

  </div>
  <!-- /.container -->

</div>
<!-- /.content-section-b -->

<div class="content-section-a">

  <div class="container">

    <div class="row center-outer">
      <div id="main-content-3" class="col-lg-5 col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading">Індивідуальна програма тренувань</h2>
        <p class="lead">Отримайте програму на основі індивідуальних даних, що враховує  особливості організму та рівень підготовленості.
        </p>
        <%= link_to 'Отримати', individual_program_path, class: 'btn btn-lg square-btn' %>
      </div>
      <div class="col-lg-5 col-lg-offset-2 col-sm-6 center-inner">
        <%= image_tag('main/content-image-3.jpg', class: 'img-responsive img-rounded', id: 'content-image-3') %>
      </div>
    </div>

  </div>
  <!-- /.container -->

</div>
<!-- /.content-section-a -->

app/views/home/_timeline.html.erb
<section id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading"> Розпочніть зараз </h2>
        <h3 class="section-subheading text-muted"> Станьте сильніше, швидше та впевненіше </h3>
        <br>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <ul class="timeline">
          <li id="time-line-1">
            <%= link_to '', new_user_registration_path, {class: 'timeline-image image-align'}%>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4><br></h4>
                <h4 class="subheading">Зареєструйтеся</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted"> Створіть особистий обліковий запис, використовуючи поштову скриньку або соціальну мережу Faceebook</p>
              </div>
            </div>
          </li>
          <li id="time-line-2" class="timeline-inverted">
            <%= link_to '', all_programs_path, {class: 'timeline-image image-align'}%>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4><br></h4>
                <h4 class="subheading"> Підберіть план тренувань </h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted"> Виберіть готову, отримайте індивідуальну, створену на основі особистих даних, або створіть власну програму </p>
              </div>
            </div>
          </li>
          <li id="time-line-3">
            <%= link_to '', user_signed_in? ? user_events_path(current_user) : new_user_registration_path, {class: 'timeline-image image-align'}%>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4><br></h4>
                <h4 class="subheading">Організуйте тренувальний процес</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted"> Розпишіть календар тренувань, щоб не пропустити заняття та отримувати сповіщення </p>
              </div>
            </div>
          </li>
          <li id="time-line-4" class="timeline-inverted">
            <%= link_to '', user_signed_in? ? user_parameters_path(current_user) : new_user_registration_path, {class: 'timeline-image image-align'}%>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4><br></h4>
                <h4 class="subheading"> Відслідковуйте прогрес </h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted"> Періодично проводьте заміри свого тіла та спостерігайте за змінами</p>
              </div>
            </div>
          </li>
          <li id="time-line-5" class="timeline-inverted">
            <%= link_to root_path, {class: 'timeline-image image-align'} do%>
                <h4> Досягайте
                  <br> своєї <br> мети
                </h4>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<%= render 'carousel'%>
<%= render 'main_blocks'%>
<%= render 'timeline'%>