config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  root 'home#index'

  get 'exercises/group/:id' => 'exercises#group', as: 'exercises_group'

  get 'programs/filter' => 'programs#filter', as: 'program_filter'

  get 'programs/assign_to_user' => 'programs#assign_to_user', as: 'assign_program'

  get '/programs' => 'programs#all_programs', as: 'all_programs'

  get '/programs/:id' => 'programs#common_program', as: 'common_program'

  get '/individual' => 'programs#individual', as: 'individual_program'
  post '/create_individual' => 'programs#create_individual', as: 'create_individual_program'

  resources :exercises, only: [:index, :show]
  resources :users do
    resources :programs, controller: 'programs', as: 'training_programs'
    resources :parameters, controller: 'parameters'
    resources :events, controller: 'events'
  end

  get 'training_days/:id/edit' => 'training_days#edit', as: 'edit_training_day'

  get 'training_days/:id/change_exercise' => 'training_days#change_exercise', as: 'change_exercise'

  delete 'training_days/:id/delete_exercise' => 'training_days#delete_exercise', as: 'delete_exercise'

end

app/models/program_type.rb
class ProgramType < ActiveRecord::Base
  has_many :training_programs
  validates :name, presence: true
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :check_user, only: [:index]
  before_action :program_info, only: [:show, :common_program]
  before_action  :authenticate_user!, except: [:all_programs, :common_program, :assign_to_user, :filter]
  def index
    @user = current_user
    @programs = @user.training_programs
  end

  def show
  end

  def edit
    @program = TrainingProgram.find(params[:id])
    @exercises = Exercise.all
  end

  def update
    @program = TrainingProgram.find(params[:id])
    if @program.update(program_params)
      redirect_to [current_user, @program]
    else
      render 'edit'
    end
  end

  def individual
    @program = TrainingProgram.new
  end

  def create_individual
    #render text: individual_params[:joint_pain]
    #@program = TrainingProgram.generate_program(individual_params, current_user)
    @program = TrainingProgram.generate_program(individual_params, current_user)
    #render json: @program.training_days[0].training_day_exercises
    redirect_to user_training_program_path(current_user, @program)
  end

  def filter
    @programs = TrainingProgram.filter(params.slice(:body_type, :program_type, :male_type))
    respond_to do |format|
      format.js
    end
  end

  def assign_to_user
    @program = TrainingProgram.find(params[:program])
    unless current_user.has_program? @program
      @program.duplicate_program(current_user)
    end
    respond_to do |format|
      format.js
    end
  end

  def all_programs
    @programs = TrainingProgram.includes(:program_type).all
    @body_types = TrainingProgram.body_types
    @male_types = User.male_types
  end

  def common_program
    render action: 'show'
  end

  private
  def program_info
    @program = TrainingProgram.find(params[:id])
    info = @program.days_count
    @days_count = info[0]
    @ex_count = info[1]
    @author = @program.get_author
  end

  def program_params
    params.require(:training_program).permit(:name, :description, :program_type_id, :body_type, :male_type, :program_image)
  end

  def individual_params
    params.permit(:height, :weight, :program_type_id, :body_type, :male_type, :age, :workout_1, :workout_2, :workout_3, :user_id, joint_pain: [])
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/partials/_assign_program.html.erb
<% if user_signed_in? %>
    <% if current_user.has_program?(@program) %>
        <%= link_to 'Редагувати', edit_user_training_program_path(current_user, @program), class: 'btn btn-lg square-btn'%>
    <% else %>
        <%= link_to 'Додати у вибране', assign_program_path(program: @program), remote: true, class: 'btn btn-lg square-btn' %>
    <% end %>
<% else %>
    <%= link_to 'Увійти', new_user_registration_path, class:'btn btn-lg btn-primary', role: 'button' %>
<% end %>

app/views/programs/partials/_edit_exercise_form.html.erb
<%= form_tag(change_exercise_path(day_exercise: day_exercise, index: index), method: :get, remote: true) do %>
    <% unless errors.nil? %>
        <div id="error_explanation" class=" alert alert-danger">
          <h2><%= pluralize(errors.count, "error") %> prohibited this exercise from being changed:</h2>
          <ul>
            <% errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= text_field_tag :sets, day_exercise.sets, placeholder: 'Кількість підходів',class: 'form-control' %>
    <%= text_field_tag :repetitions, day_exercise.repetitions,  placeholder: 'Кількість повторів',class: 'form-control' %>
    <%= text_field_tag :rest, day_exercise.rest, placeholder: 'Час відпочинку',class: 'form-control' %>
    <%= select_tag :exercise, options_from_collection_for_select(exercises, 'id', 'name', day_exercise.exercise.id),class: 'form-control select'%>
    <%= submit_tag 'Редагувати' , class: 'form-control btn btn-md btn-primary'%>
<% end %>

app/views/programs/partials/_programs_list.html.erb
<% programs.each do |program| %>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
      <%= link_to common_program_path(program), class: 'program-link' do %>
          <div class="program-wrap">
            <div class="image-wrapper overlay-fade-in">
              <%= image_tag(program.program_image.url) %>
              <h3 class="program-name"><%= program.name %></h3>
            </div>
            <div class="program-description ">
              <div class="description-block inline">
                <div class="block-heading text-muted">
                  Ціль тренувань:
                </div>
                <div class="block-info">
                  <%= !program.program_type.nil? && program.program_type.name.present?  ? program.program_type.name : 'Будь-яка' %>
                </div>
              </div>
              <div class="description-block inline">
                <div class="block-heading text-muted">
                  Тілобудова:
                </div>
                <div class="block-info">
                  <%= program.body_type.present? ? program.body_type :  'Будь-яка' %>
                </div>
              </div>
              <div class=" description-block inline">
                <div class="block-heading text-muted">
                  Стать:
                </div>
                <div class="block-info">
                  <%= program.male_type.present? ? program.male_type : 'Будь-яка' %>
                </div>
              </div>
            </div>
          </div>

      <% end %>
    </div>
<% end %>