config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  root 'home#index'

  get 'exercises/group/:id' => 'exercises#group', as: 'exercises_group'

  get 'programs/filter' => 'programs#filter', as: 'program_filter'

  get 'programs/assign_to_user' => 'programs#assign_to_user', as: 'assign_program'

  get '/programs' => 'programs#all_programs', as: 'all_programs'

  get '/programs/:id' => 'programs#common_program', as: 'common_program'

  get '/individual' => 'programs#individual', as: 'individual_program'
  post '/create_individual' => 'programs#create_individual', as: 'create_individual_program'

  resources :exercises, only: [:index, :show]
  resources :users do
    resources :programs, controller: 'programs', as: 'training_programs'
    resources :parameters, controller: 'parameters'
    resources :events, controller: 'events'
  end

  get 'training_days/:id/edit' => 'training_days#edit', as: 'edit_training_day'

  get 'training_days/:id/change_exercise' => 'training_days#change_exercise', as: 'change_exercise'

  delete 'training_days/:id/delete_exercise' => 'training_days#delete_exercise', as: 'delete_exercise'

end

app/views/navigation/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul class="list-inline">
          <li>
            <%= link_to 'Головна', root_path %>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <%= link_to 'Програми', all_programs_path %>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <%= link_to 'Вправи', exercises_path %>
          </li>
        </ul>
        <p class="copyright text-muted small">Copyright &copy; Maruniak Stanislav 2016. Усі права захищено</p>
      </div>
    </div>
  </div>
</footer>

app/views/navigation/_navbar.html.erb
<nav id="mainNav"  class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header ">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%= image_tag('common/logopftd1.png', id: 'navbar-logo') %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
      <ul class="nav navbar-nav">
        <li class="dropdown mega-dropdown">
          <%= link_to all_programs_path, class: 'nav-link dropdown-toggle  disabled', 'data-toggle' => 'dropdown', 'data-hover' => 'dropdown' do %>
              Програми
          <% end %>
        </li>
        <li class="dropdown mega-dropdown">
          <%= link_to exercises_path, class: 'nav-link dropdown-toggle  disabled', 'data-toggle' => 'dropdown', 'data-hover' => 'dropdown' do %>
            Вправи <span class="caret"></span>
          <% end %>
          <div class="dropdown-menu mega-dropdown-menu ">
            <div class="container-fluid">
              <!-- Tab panes -->
              <div class="tab-content">
                <div class="tab-pane active" id="groups">
                  <ul class="nav-list list-inline">
                    <% @muscle_groups.each do |group| %>
                      <li><%= link_to exercises_group_path(group) do %> <%= image_tag(group.muscle_group_image.url, class: 'nav-image') %> <span> <%= group.name %> </span> <% end %></li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class="dropdown">
              <%= link_to current_user.username, root_path, class:'nav-link dropdown-toggle', 'data-toggle' => 'dropdown' %>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to 'Особистий кабінет', user_path(current_user) %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to 'Календар тренувань', user_events_path(current_user) %>
                </li>
                <li>
                  <%= link_to 'Щоденник прогресу', user_parameters_path(current_user) %>
                </li>
                <li>
                  <%= link_to 'Мої програми', user_training_programs_path(current_user) %>
                </li>
                <li class="divider"></li>
                <li><%= link_to 'Вийти', destroy_user_session_path, method: :delete %></li>

              </ul>
            </li>
        <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Увійти</b> <span class="caret"></span></a>
              <ul id="login-dp" class="dropdown-menu">
                <li>
                  <div class="row">
                    <div class="col-md-12">
                      <%= form_for(resource, as: resource_name, url: session_path(resource_name), id:'login-nav')  do |f| %>
                        <div class="form-group">
                          <label class="sr-only" for="exampleInputEmail2">Email address</label>
                          <%= f.text_field :login, autofocus: true, class: 'form-control', placeholder: 'Username or email', required: true %>
                        </div>
                        <div class="form-group">
                          <label class="sr-only" for="exampleInputPassword2">Password</label>
                          <%= f.password_field :password, class: 'form-control', placeholder: 'Password', id: 'exampleInputPassword2', required: true  %>
                        </div>
                        <div class="help-block text-right">
                          <%= link_to 'Забули пароль?', new_password_path(resource_name) %>
                        </div>
                        <% if devise_mapping.rememberable? -%>
                          <div class="checkbox">
                            <label>
                              <%= f.check_box :remember_me %> Запам’ятати мене
                            </label>
                          </div>
                        <% end -%>
                        <div class="form-group">
                          <%= f.submit 'Увійти', class: 'btn btn-primary btn-block'%>
                        </div>
                      <% end %>
                      <div class="social-buttons">
                        <%= link_to omniauth_authorize_path(resource_name, :facebook), class: 'btn btn-fb' do %>
                            <i class="fa fa-facebook"></i> | Увійти з допомогою Facebokk
                        <% end %>
                      </div>
                    </div>
                    <div class="bottom text-center">
                      Вперше тут? <%= link_to new_user_registration_path  do %><b> Приєднуйтеся! </b><%end%>
                    </div>
                  </div>
                </li>
              </ul>
            </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>